#!/bin/bash
commit_msg=$(cat "$1")
$msg="Nous somme l’équipe 1, composé de Tom, Alex, Romain, Thibault et Théo"
# Vérifie si le message de commit se termine par 'bye'
if [[ "$commit_msg" =~ $msg ]]; then
    echo "Commit message termine par '$msg'. Commit autorisé."
    exit 0  # Exit with success (commit allowed)
else
    echo "Le message de commit doit se terminer par '$msg'. Commit rejeté."
    exit 1  # Exit with failure (commit disallowed)
fi
