#!/bin/bash
commit_msg=$(cat "$1")
# Vérifie si le message de commit se termine par 'Nous somme l’équipe 1, composé de Tom, Alex, Romain, Thibault et Théo'
if [[ "$commit_msg" =~ Nous somme l’équipe 1, composé de Tom, Alex, Romain, Thibault et Théo$ ]]; then
    echo "Le message de commit doit se terminer par un point d'exclamation (!). Commit rejeté."
    exit 1  # Exit with failure (commit disallowed)
else
    echo "Commit autorisé."
    exit 0  # Exit with success (commit allowed)
fi
